---
title: "Which party wins in each NC district?"
output: html_document
---

https://www.pewresearch.org/politics/2020/10/21/large-shares-of-voters-plan-to-vote-a-straight-party-ticket-for-president-senate-and-house/ => resource to justify using the presidential predictions for congressional elections!



```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(readr)
library(groupdata2)
library(lme4)
```


```{r setup, include=FALSE}
last_day_to_register <- as.Date("11/08/2016", format= "%m/%d/%Y")
# last_day_to_register <- as.Date("11/06/2012", format= "%m/%d/%Y")
nc_registered_voters <- readr::read_rds("ncvoter_Statewide_small_2016.rds")  # nc registered voters

nc_registered_voters <- nc_registered_voters %>% 
  filter(voter_status_reason_desc != "DECEASED") %>%
  mutate(voter_reg_num = as.integer(substr(voter_reg_num,6,12)))

nc_registered_voters$registr_dt <- as.character(nc_registered_voters$registr_dt)
nc_registered_voters$registr_dt<- as.Date(nc_registered_voters$registr_dt, format= "%m/%d/%Y")
nc_registered_voters <- subset(nc_registered_voters, registr_dt <= last_day_to_register)
```


```{r setup, include=FALSE}
nc_voters <- read.csv("ncvhis_Statewide_small_2016.csv") # voters in year

voter_data <- inner_join(nc_registered_voters,nc_voters %>% filter(voted_party_desc != ""),by=c("voter_reg_num", "county_id", "county_desc"))
```



```{r setup, include=FALSE}
voter_data <- voter_data %>% 
  mutate(
         age_bin = case_when(
           birth_age <= 29 ~ "18-29",
           birth_age >= 30 & birth_age <= 39 ~ "30-39",
           birth_age >= 40 & birth_age <= 49 ~ "40-49",
           birth_age >= 50 & birth_age <= 64 ~ "50-64",
           birth_age >= 65 ~ "65+"
         ),
         race_ethnicity = case_when(
           ethnic_code == "HL" ~ "Hispanic Any Race",
           ethnic_code == "NL" & race_code == "W" ~ "Non-Hispanic White",
           ethnic_code == "NL" & race_code == "B" ~ "Non-Hispanic Black",
           ethnic_code == "NL" & race_code == "O" ~ "Non-Hispanic Other",
           ethnic_code == "NL" & race_code == "A" ~ "Non-Hispanic Asian",
           ethnic_code == "NL" & race_code == "M" ~ "Non-Hispanic Mixed",
           ethnic_code == "NL" & race_code == "I" ~ "Non-Hispanic American Indian",
           ethnic_code == "NL" & race_code == "P" ~ "Non-Hispanic Pacific Islander",
           ethnic_code == "NL" & race_code == "U" ~ "Undetermined",
           TRUE ~ "Undetermined"
         ),
         voted_party_desc = case_when(
           voted_party_desc == "DEMOCRATIC" ~ "DEMOCRATIC",
           voted_party_desc == "REPUBLICAN" ~ "REPUBLICAN",
           voted_party_desc== "UNAFFILIATED" ~ "UNAFFILIATED",
           voted_party_desc %in% c("LIBERTARIAN", "GREEN", "CONSTITUTION") ~ "THIRD PARTY",
           TRUE ~ as.character(voted_party_desc)
         )
         
  )

grouped_voter_only_data <- voter_data %>%
  dplyr::group_by(county_desc, cong_dist_abbrv, race_ethnicity, party_cd,
                  age_bin, gender_code) %>%
  dplyr::summarize(Democrat = sum(voted_party_cd=="DEM"),
                   Republican = sum(voted_party_cd=="REP"),
                   total = n())

grouped_voter_only_data <- grouped_voter_only_data  %>% dplyr::rename(gender = gender_code)
grouped_voter_only_data <- grouped_voter_only_data %>% filter(party_cd != "CST")
grouped_voter_only_data <- grouped_voter_only_data %>% filter(party_cd != "GRE")
grouped_voter_only_data <- grouped_voter_only_data %>% filter(party_cd != "LIB")

grouped_voter_only_data <- grouped_voter_only_data %>% filter(gender != "U")
grouped_voter_only_data <- grouped_voter_only_data %>% filter(race_ethnicity != "Undetermined")
grouped_voter_only_data <- grouped_voter_only_data %>% filter(!is.na(gender))
grouped_voter_only_data <- grouped_voter_only_data %>% filter(race_ethnicity != "Non-Hispanic Other")
grouped_voter_only_data <- grouped_voter_only_data %>% filter(race_ethnicity != "Non-Hispanic Pacific Islander")
```


```{r setup, include=FALSE}
district1 <- c("VANCE", "WARREN", "HALIFAX", "NORTHAMPTON", "HERTFORD", "GATES", "NASH", "EDGECOMBE", "MARTIN", "BERTIE", "WASHINGTON", "WILSON", "WAYNE", "GREENE", "PITT")
district2 <- c("WAKE")
district3 <-c("CURRITUCK", "CAMDEN", "PASQUOTANK", "PERQUIMANS", "CHOWAN", "DARE", "TYRRELL", "HYDE", "BEAUFORT", "PAMLICO", "CARTERET", "CRAVEN", "PITT", "LENOIR", "JONES", "ONSLOW", "DUPLIN")
length(district3)
district4 <-c("GRANVILLE", "ORANGE", "WAKE", "DURHAM", "FRANKLIN", "CHATHAM")
district5 <-c("WATAUGA", "ASHE", "ALLEGHANY", "WILKES", "ALEXANDER", "CALDWELL", "BURKE", "CLEVELAND", "GASTON", "RUTHERFORD")
district6 <-c("FORSYTH","GUILFORD")
district7 <-c("JOHNSTON", "SAMPSON", "BRUNSWICK", "PENDER", "NEW HANOVER","COLUMBUS", "BLADEN", "HARNETT")
district8 <-c("CABARRUS", "STANLY", "MONTGOMERY", "MOORE", "LEE", "CUMBERLAND", "HARNETT")
district9 <-c("MECKLENBURG", "UNION", "ANSON", "RICHMOND", "SCOTLAND", "MOORE", "HOKE", "ROBESON")
district10 <-c("SURRY", "STOKES", "ROCKINGHAM", "FORSYTH", "YADKIN", "IREDELL", "CATAWBA", "LINCOLN")
district11 <-c("CHEROKEE", "CLAY", "GRAHAM", "SWAIN", "MACON", "JACKSON", "HAYWOOD", "TRANSYLVANIA", "HENDERSON", "BUNCOMBE", "MADISON", "YANCEY", "MITCHELL", "AVERY", "MCDOWELL", "RUTHERFORD", "POLK")
district12 <-c("MECKLENBURG")
district13 <-c("CASWELL", "PERSON", "ALAMANCE", "CHATHAM", "LEE", "RANDOLPH", "DAVIDSON", "DAVIE", "ROWAN")

multiple <- c("RUTHERFORD", "FORSYTH", "MECKLENBURG", "MOORE", "CHATHAM", "LEE", "WAKE", "HARNETT", "PITT")

grouped_voter_only_data <- grouped_voter_only_data %>% mutate(cong_dist_abbrv = case_when(
    !(county_desc %in% multiple) & county_desc %in% district1 ~ as.integer(1),
    !(county_desc %in% multiple) & county_desc %in% district2 ~ as.integer(2),
    !(county_desc %in% multiple) & county_desc %in% district3 ~ as.integer(3),
    !(county_desc %in% multiple) & county_desc %in% district4 ~ as.integer(4),
    !(county_desc %in% multiple) & county_desc %in% district5 ~ as.integer(5),
    !(county_desc %in% multiple) & county_desc %in% district6 ~ as.integer(6),
    !(county_desc %in% multiple) & county_desc %in% district7 ~ as.integer(7),
    !(county_desc %in% multiple) & county_desc %in% district8 ~ as.integer(8),
    !(county_desc %in% multiple) & county_desc %in% district9 ~ as.integer(9),
    !(county_desc %in% multiple) & county_desc %in% district10 ~ as.integer(10),
    !(county_desc %in% multiple) & county_desc %in% district11 ~ as.integer(11),
    !(county_desc %in% multiple) & county_desc %in% district12 ~ as.integer(12),
    !(county_desc %in% multiple) & county_desc %in% district13 ~ as.integer(13),
    TRUE ~ cong_dist_abbrv
  ))

t <- grouped_voter_only_data
grouped_voter_only_data <- t
for (m in multiple){
  for (a in unique(grouped_voter_only_data$age_bin)){
    for (r in unique(grouped_voter_only_data$race_ethnicity)){
      for (p in unique(grouped_voter_only_data$party_cd)){
        for (g in unique(grouped_voter_only_data$gender))
          {
            curr = grouped_voter_only_data %>% filter(county_desc==m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & is.na(cong_dist_abbrv))
            if (nrow(curr) == 0){
              next
            }
            curr.dist = grouped_voter_only_data %>% filter(county_desc==m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & !is.na(cong_dist_abbrv))
            if (nrow(curr.dist) == 0){
              next
            }
            number.dem.from.na <- curr[,7]
            number.rep.from.na <-curr[,8]
            
            all.dem <- number.dem.from.na$Democrat
            add.to.first.dem <- as.integer(all.dem/2)
            
            all.rep <- number.rep.from.na$Republican
            add.to.first.rep <- as.integer(all.rep/2)
            
            first.county <- min(unique(curr.dist$cong_dist_abbrv))
            print(first.county)
            second.county <- max(unique(curr.dist$cong_dist_abbrv))
            
            grouped_voter_only_data <- grouped_voter_only_data  %>% 
              mutate(Democrat= case_when(
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == first.county ~ Democrat + add.to.first.dem,
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == second.county ~ Democrat + all.dem - add.to.first.dem,
                TRUE ~ Democrat
              ),
                    Republican=case_when(
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == first.county ~ Republican + add.to.first.rep,
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == second.county ~ Republican + all.rep - add.to.first.rep,
                TRUE ~ Republican
              ))
            
            
        }

    
      }

    }

  }
  print(m)
  print(nrow(grouped_voter_only_data))

}
```


```{r setup, include=FALSE}
grouped_voter_only_data <- grouped_voter_only_data %>% filter(!is.na(cong_dist_abbrv))
```


```{r setup, include=FALSE}
grouped_voter_only_data %>% write_csv("grouped_voter_only_data_2016.csv")
```


# EDA

```{r}
grouped_voter_only_data <- read_csv("grouped_voter_only_data_2016.csv")
```


```{r}
grouped_voter_only_data  <- grouped_voter_only_data %>% filter(!is.na(gender))
grouped_voter_only_data <- grouped_voter_only_data %>% filter(race_ethnicity != "Non-Hispanic Other")
```

```{r}
grouped_voter_only_data <-grouped_voter_only_data %>% ungroup()
```


```{r}
# This code chunk prefaces some of the other package load-ins because of conflicts with select fuctionality 
grouped_voter_only_data %>% 
  filter(gender %in% c("F", "M")) %>%
  mutate(sums = Democrat + Republican) %>%
  mutate(race_ethnicity = case_when(
    race_ethnicity == "Hispanic Any Race" ~  paste0("Hispanic Any Race (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Hispanic Any Race") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic American Indian" ~  paste0("Non-Hispanic American Indian (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic American Indian") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Asian" ~ paste0("Non-Hispanic Asian (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic Asian") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Black" ~ paste0("Non-Hispanic Black (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican)  %>%
                                                     filter(race_ethnicity == "Non-Hispanic Black") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Mixed" ~ paste0("Non-Hispanic Multi-Racial (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican)  %>%
                                                     filter(race_ethnicity == "Non-Hispanic Mixed") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic White" ~ paste0("Non-Hispanic White (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican)  %>%
                                                     filter(race_ethnicity == "Non-Hispanic White") %>%
                                                     summarise(sum(sums)),
                                                   ")")
  )) %>%
  dplyr::select(race_ethnicity, age_bin, gender, Democrat, Republican) %>%
  dplyr::group_by(race_ethnicity, age_bin, gender) %>% 
  dplyr::summarize(Democrat = sum(Democrat), 
                   Republican = sum(Republican), 
                   proportion = Democrat/(Democrat+Republican)) %>% ungroup()%>% 
  ggplot(aes(x = age_bin, y = proportion, fill = gender)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  facet_wrap(~race_ethnicity, nrow = 2) + 
  geom_text(aes(label=paste0(sprintf("%.2f", proportion)), y=proportion/2), 
            position = position_dodge(width = 1),  
            colour="Black", 
            size = 2.2) + 
  labs(x = expression("Age Group"), 
       y= ("Proportion of Democratic Voters"), 
       title = "Democratic Voters Across Age Groups, Race/Ethnicity, and Sex", 
       caption="Figure 1a") +
  theme(plot.caption = element_text(hjust = 0.5, vjust = -0.5, size = 12)) +
  guides(fill=guide_legend(title="Sex"))
```

```{r EDA party, fig.width=9, fig.align="center", warning=F,message=F,echo=FALSE,results='hide',fig.keep='all'}
# This code chunk prefaces some of the other package load-ins because of conflicts with select fuctionality 
grouped_voter_only_data %>% 
  mutate(sums = Democrat + Republican) %>%
  mutate(race_ethnicity = case_when(
    race_ethnicity == "Hispanic Any Race" ~ paste0("Hispanic Any Race (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Hispanic Any Race") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic American Indian" ~ paste0("Non-Hispanic American Indian (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic American Indian") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Asian" ~ paste0("Non-Hispanic Asian (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic Asian") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Black" ~ paste0("Non-Hispanic Black (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic Black") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic Mixed" ~ paste0("Non-Hispanic Multi-Racial (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic Mixed") %>%
                                                     summarise(sum(sums)),
                                                   ")"),
    race_ethnicity == "Non-Hispanic White" ~ paste0("Non-Hispanic White (n=",
                                                   grouped_voter_only_data %>%
                                                     mutate(sums = Democrat + Republican) %>%
                                                     filter(race_ethnicity == "Non-Hispanic White") %>%
                                                     summarise(sum(sums)),
                                                   ")")
  )) %>%
  dplyr::select(race_ethnicity, age_bin, party_cd,Democrat,Republican) %>%
  dplyr::group_by(race_ethnicity, age_bin, party_cd) %>% 
  dplyr::summarize(Democrat = sum(Democrat), 
                   Republican = sum(Republican), 
                   proportion = Democrat/(Democrat + Republican)) %>% ungroup() %>% 
  ggplot(aes(x = age_bin, y = proportion, fill = party_cd)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  facet_wrap(~race_ethnicity, nrow = 2) + 
  geom_text(aes(label=paste0(sprintf("%.2f", proportion)), y=proportion/2), 
            position = position_dodge(width = 1),  
            colour="Black", 
            size = 2.2) + 
  labs(x = expression("Age Group"), 
       y= ("Proportion of Democratic Voters"), 
       title = "Democratic Voters Across Age Groups, Race/Ethnicity, and Party Affiliation", 
       caption="Figure 1b") +
  theme(plot.caption = element_text(hjust = 0.5, vjust = -0.5, size = 12)) +
  guides(fill=guide_legend(title="Party"))
```

```{r EDA gender, fig.width=9, fig.align="center", warning=F,message=F,echo=FALSE,results='hide',fig.keep='all'}
# This code chunk prefaces some of the other package load-ins because of conflicts with select fuctionality 
edap1c <- who_votes_data %>% 
  mutate(sums = Likely + Unlikely) %>%
  dplyr::select(gender, age_bin, party_cd,Likely,Unlikely) %>%
  dplyr::group_by(gender, age_bin, party_cd) %>% 
  dplyr::summarize(Likely = sum(Likely), 
                   Unlikely = sum(Unlikely), 
                   proportion = Likely/(Likely+Unlikely)) %>% ungroup() %>% 
  ggplot(aes(x = age_bin, y = proportion, fill = party_cd)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  facet_wrap(~gender, nrow = 1) + 
  geom_text(aes(label=paste0(sprintf("%.2f", proportion)), y=proportion/2), 
            position = position_dodge(width = 1),  
            colour="Black", 
            size = 2.2) + 
  labs(x = expression("Age Group"), 
       y= ("Proportion of Likely Voters"), 
       title = "Likely Voters Across Age Groups, Gender, and Party Affiliation", 
       caption="Figure 1c") +
  theme(plot.caption = element_text(hjust = 0.5, vjust = -0.5, size = 12)) +
  guides(fill=guide_legend(title="Party"))
```


```{r EDA county map, fig.width=5.5, fig.height=2.5,fig.align="center", warning=F,message=F,echo=FALSE,results='hide',fig.keep='all'}
# http://www.peterhaschke.com/r/2013/12/05/NCmaps.html
map <- map_data("county")
nc <- subset(map, region =="north carolina")
nc$subregion <- toupper(nc$subregion)
nc <- nc %>% dplyr::rename(county_desc=subregion)
dem.by.county <- grouped_voter_only_data %>% dplyr::select(everything()) %>%
  dplyr::group_by(county_desc) %>% 
  dplyr::summarise(Democrat=sum(Democrat),
                   Republican=sum(Republican),
                   Prop=sum(Democrat)/(sum(Democrat) + sum(Republican)))
mapdata <- merge(nc, dem.by.county, by = "county_desc")
# fix gray background, make lines darker, find a better color than purple, make borders lighter color
ggplot(data=mapdata) + 
  labs(caption="Figure 2a") +
  geom_polygon(aes(x=long, y=lat, group = group, fill = Prop),colour = "#202020", size=.8) +
  scale_fill_gradient2(high="#454545", low="#b1b1b1", "% Democratic Voters") +
  theme(legend.title = element_text(size = 10), axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank(),
    panel.grid = element_blank(), legend.position=c(.2,.2), plot.caption = element_text(hjust = 0.5, vjust = -0.5, size = 12), 
    legend.key.width = unit(1.7,"line"), legend.key.height = unit(.8,"line")) +
  guides(fill = guide_colorbar(title.position = "top", direction = "horizontal"), shape = guide_legend(override.aes = list(size = 0.5))) 

```


# Model

```{r}
grouped_voter_only_data <- grouped_voter_only_data %>% filter(gender %in% c("M", "F"))
```


```{r}
# cross validation for model!
set.seed(1540825)
fold_df <- groupdata2::fold(grouped_voter_only_data, k = 5, cat_col = c("age_bin", "race_ethnicity", "gender","county_desc", "cong_dist_abbrv", "party_cd")) %>%
  dplyr::mutate(vote = ifelse(Democrat/(Democrat+Republican) > 0.5, 1, 0),
                vote = ifelse(is.nan(Democrat/(Democrat+Republican)), 0, vote),
                vote = dplyr::case_when(
                  Democrat == 0 & Republican == 0 ~ 0,
                  TRUE ~ vote
                ))

cross_validation <- function(model_formula, grouped_voter_only_data){
  
  acc_list = c()
  f1_list = c()
  AUC_list = c()
  for (i in 1:5) {
    print(i)
    train <- grouped_voter_only_data %>% filter(.folds != i)
    test <- grouped_voter_only_data %>% filter(.folds == i)
  
    glmer.fit <- glmer(model_formula,
                     data = train,
                     family = binomial,
                     control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)))
  
    glmer.probs <- predict(glmer.fit,  test,  type = "response")
    glmer.pred <- rep(0, nrow(test))
    glmer.pred[glmer.probs > 0.5] <- 1
  
    acc_list[i] <-  mean(glmer.pred == test$vote)
    f1_list[i] <- (caret::confusionMatrix(glmer.pred %>% as.factor(), test$vote %>% as.factor()))$byClass["F1"]
      AUC_list[i] <- cvAUC::AUC(glmer.pred %>% as.double(), test$vote %>% as.double())
    }
    
    acc_mean = acc_list %>% mean(na.rm=T) %>% round_perc()
    acc_sd = acc_list %>% sd(na.rm=T) %>% round_perc()
    f1_mean = f1_list %>% mean(na.rm=T)  %>% round_perc()
    f1_sd = f1_list %>% sd(na.rm=T)  %>% round_perc()
    AUC_mean = AUC_list %>% mean(na.rm=T)  %>% round_perc()
    AUC_sd = AUC_list %>% sd(na.rm=T)  %>% round_perc()
    
    cv_df <- tibble(
      Accuracy = paste0(acc_mean, "% ± ", acc_sd, "%"),
      F1 = paste(f1_mean, "±", f1_sd),
      AUC = paste(AUC_mean, "±", AUC_sd))
    
  return(cv_df)
}
```

```{r}

# model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + age_bin * race_ethnicity + (1|cong_dist_abbrv)"
# seed: 658392
# accuracy: 60%

#model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + age_bin * race_ethnicity + (1|cong_dist_abbrv) + (1|county_desc)"
#seed: 658392
# accuracy: 70% => i like this one!!!

#model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + age_bin * race_ethnicity + (1|cong_dist_abbrv) + (1+age_bin|county_desc)"
#BAD

#model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + party_cd * race_ethnicity + (1|cong_dist_abbrv) + (1|county_desc)"
#seed: 658392
# accuracy: 68% => ALSO GOOD!

#model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + (1|cong_dist_abbrv) + (1|county_desc)"
#seed: 658392
#accuracy: 68.35

model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + party_cd * age_bin + (1|cong_dist_abbrv) + (1|county_desc)"
#seed: 658392
# accuracy:68.9 



df <- cross_validation(model.formula, fold_df)
```



```{r}
#best model is: 
model.formula <- "cbind(Democrat, Republican) ~ age_bin + race_ethnicity + gender + party_cd + age_bin * race_ethnicity + (1|cong_dist_abbrv) + (1|county_desc)"

#train on everything!
glmer.fit <- glmer(model.formula,
                     data = grouped_voter_only_data,
                     family = binomial,
                     control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)))
  
glmer.probs <- predict(glmer.fit,  grouped_voter_only_data,  type = "response")

#
```

```{r}
grouped_voter_only_data$pred_prob <- glmer.probs
```

```{r}
likely_2020 <- read_csv("likely_voters_2020.csv")
only_likely <- likely_2020 %>%
  filter(predicted_likely != 0) %>%
  select(-c(pred_prob, total))
```

```{r}
likely_2020_with_pred_prob <- inner_join(grouped_voter_only_data, only_likely, by=c("age_bin", "race_ethnicity", "gender", "party_cd", "county_desc", "cong_dist_abbrv"))
```

```{r}

vote_shares_by_district <- function(district){
  dem_vote_shares <- c()
  district_df <- likely_2020_with_pred_prob %>% filter(cong_dist_abbrv == district)
  totals <- district_df$predicted_likely
  probs <- district_df$pred_prob

  for (j in 1:1000){
    set.seed(j)
    n_likely_dem <- c()
    for (i in 1:length(totals)){
  #binomial parameters
      total <- totals[i]
      prob <- probs[i]
      likely <- sum(rbinom(total,1,prob))
     n_likely_dem[i] <- likely
  }

  likely_2020_with_pred_prob$predicted_likely_dems <- n_likely_dem #likely democratic voters in each group
  by_district <- likely_2020_with_pred_prob %>% 
    group_by(cong_dist_abbrv) %>%
    summarize(total = sum(predicted_likely), dems = sum(predicted_likely_dems)) %>%
    mutate(dem_vote_share <- dems/total)
  dem_vote_shares[i] <- by_district$dem_vote_share


  }
  return(dem_vote_shares)
}
```

```{r}
districts <- unique(likely_2020_with_pred_prob$cong_dist_abbrv)
df <- data.frame(matrix(ncol = length(districts), nrow = 1000))
colnames(df) <- districts
i = 1
for (district in districts){
  simulated_district_shares <- vote_shares_by_district(district)
  df[, i] <- simulated_district_shares
  
  i = i + 1
}
```

