---
title: "create_congressional_districts_data"
author: "Anna Darwish"
date: "11/2/2020"
output: pdf_document
---

```{r, function checking for installed packages, include=FALSE}
# Validate that all necessary packaged have been downloaded, install otherwise or throw err package DNE
pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,repos = "http://cran.r-project.org", dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}
```

```{r package test, include=FALSE}
# Installing packages 
# Additionally, if you are struggling to download RJags, please visit the following link for help. It can also help to try to download the package locally or in RStudio Cloud: https://sites.google.com/a/utexas.edu/edm-principalstratification/downloading-installing-r-jags-rstudio
pkgTest("tidyverse")
pkgTest("dplyr")
pkgTest("lubridate")
pkgTest("readr")
pkgTest("groupdata2")
pkgTest("lme4")
pkgTest("pander")
pkgTest("kableExtra")
```

```{r packages load, include=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(readr)
library(groupdata2)
library(lme4)
library(knitr)
library(pander)
library(kableExtra)
```

```{r setup, include=FALSE}
last_day_to_register <- as.Date("11/08/2016", format= "%m/%d/%Y")
# last_day_to_register <- as.Date("11/06/2012", format= "%m/%d/%Y")
nc_registered_voters <- readr::read_rds("ncvoter_Statewide_small_2016.rds")  # nc registered voters

nc_registered_voters <- nc_registered_voters %>% 
  filter(voter_status_reason_desc != "DECEASED") %>% 
  mutate(voter_reg_num = as.integer(substr(voter_reg_num,6,12))) 


nc_registered_voters$registr_dt <- as.character(nc_registered_voters$registr_dt)
nc_registered_voters$registr_dt<- as.Date(nc_registered_voters$registr_dt, format= "%m/%d/%Y")
nc_registered_voters <- subset(nc_registered_voters, registr_dt <= last_day_to_register)
```


```{r setup, include=FALSE}
nc_voters <- read.csv("ncvhis_Statewide_small_2016.csv") %>%
  mutate(voter_reg_num = as.character(voter_reg_num)) %>%
  mutate(voter_reg_num = case_when(
    county_desc == "WAKE" ~ substr(voter_reg_num, 4, length(voter_reg_num)), 
    TRUE ~ voter_reg_num
  )) %>%
  mutate(voter_reg_num = as.integer(voter_reg_num))

voter_data <- left_join(nc_registered_voters,nc_voters %>% filter(voted_party_desc != ""),by=c("voter_reg_num", "county_id", "county_desc")) %>%
  filter(!is.na(voted_party_desc))

```

```{r setup, include=FALSE}
voter_data <- voter_data %>% 
  mutate(
         age_bin = case_when(
           birth_age <= 29 ~ "18-29",
           birth_age >= 30 & birth_age <= 39 ~ "30-39",
           birth_age >= 40 & birth_age <= 49 ~ "40-49",
           birth_age >= 50 & birth_age <= 64 ~ "50-64",
           birth_age >= 65 ~ "65+"
         ),
         race_ethnicity = case_when(
           ethnic_code == "HL" ~ "Hispanic Any Race",
           ethnic_code == "NL" & race_code == "W" ~ "Non-Hispanic White",
           ethnic_code == "NL" & race_code == "B" ~ "Non-Hispanic Black",
           ethnic_code == "NL" & race_code == "O" ~ "Non-Hispanic Other",
           ethnic_code == "NL" & race_code == "A" ~ "Non-Hispanic Asian",
           ethnic_code == "NL" & race_code == "M" ~ "Non-Hispanic Mixed",
           ethnic_code == "NL" & race_code == "I" ~ "Non-Hispanic American Indian",
           ethnic_code == "NL" & race_code == "P" ~ "Non-Hispanic Pacific Islander",
           ethnic_code == "NL" & race_code == "U" ~ "Undetermined",
           TRUE ~ "Undetermined"
         ),
         voted_party_desc = case_when(
           voted_party_desc == "DEMOCRATIC" ~ "DEMOCRATIC",
           voted_party_desc == "REPUBLICAN" ~ "REPUBLICAN",
           voted_party_desc== "UNAFFILIATED" ~ "UNAFFILIATED",
           voted_party_desc %in% c("LIBERTARIAN", "GREEN", "CONSTITUTION") ~ "THIRD PARTY",
           TRUE ~ as.character(voted_party_desc)
         )
         
  )

grouped_voter_data <- voter_data %>%
  dplyr::group_by(county_desc, cong_dist_abbrv, race_ethnicity, party_cd,
                  age_bin, gender_code) %>%
  dplyr::summarize(Democrat = sum(voted_party_cd=="DEM"),
                   Republican = sum(voted_party_cd=="REP"),
                   total = n())

grouped_voter_data <- grouped_voter_data  %>% dplyr::rename(gender = gender_code)
grouped_voter_data <- grouped_voter_data %>% filter(party_cd != "CST")
grouped_voter_data <- grouped_voter_data %>% filter(party_cd != "GRE")
grouped_voter_data <- grouped_voter_data %>% filter(party_cd != "LIB")

grouped_voter_data <- grouped_voter_data %>% filter(gender != "U")
grouped_voter_data <- grouped_voter_data %>% filter(race_ethnicity != "Undetermined")
grouped_voter_data <- grouped_voter_data %>% filter(!is.na(gender))
grouped_voter_data <- grouped_voter_data %>% filter(race_ethnicity != "Non-Hispanic Other")
grouped_voter_data <- grouped_voter_data %>% filter(race_ethnicity != "Non-Hispanic Pacific Islander")
```


```{r setup, include=FALSE}
district1 <- c("VANCE", "WARREN", "HALIFAX", "NORTHAMPTON", "HERTFORD", "GATES", "NASH", "EDGECOMBE", "MARTIN", "BERTIE", "WASHINGTON", "WILSON", "WAYNE", "GREENE", "PITT")
district2 <- c("WAKE")
district3 <-c("CURRITUCK", "CAMDEN", "PASQUOTANK", "PERQUIMANS", "CHOWAN", "DARE", "TYRRELL", "HYDE", "BEAUFORT", "PAMLICO", "CARTERET", "CRAVEN", "PITT", "LENOIR", "JONES", "ONSLOW", "DUPLIN")
length(district3)
district4 <-c("GRANVILLE", "ORANGE", "WAKE", "DURHAM", "FRANKLIN", "CHATHAM")
district5 <-c("WATAUGA", "ASHE", "ALLEGHANY", "WILKES", "ALEXANDER", "CALDWELL", "BURKE", "CLEVELAND", "GASTON", "RUTHERFORD")
district6 <-c("FORSYTH","GUILFORD")
district7 <-c("JOHNSTON", "SAMPSON", "BRUNSWICK", "PENDER", "NEW HANOVER","COLUMBUS", "BLADEN", "HARNETT")
district8 <-c("CABARRUS", "STANLY", "MONTGOMERY", "MOORE", "LEE", "CUMBERLAND", "HARNETT")
district9 <-c("MECKLENBURG", "UNION", "ANSON", "RICHMOND", "SCOTLAND", "MOORE", "HOKE", "ROBESON")
district10 <-c("SURRY", "STOKES", "ROCKINGHAM", "FORSYTH", "YADKIN", "IREDELL", "CATAWBA", "LINCOLN")
district11 <-c("CHEROKEE", "CLAY", "GRAHAM", "SWAIN", "MACON", "JACKSON", "HAYWOOD", "TRANSYLVANIA", "HENDERSON", "BUNCOMBE", "MADISON", "YANCEY", "MITCHELL", "AVERY", "MCDOWELL", "RUTHERFORD", "POLK")
district12 <-c("MECKLENBURG")
district13 <-c("CASWELL", "PERSON", "ALAMANCE", "CHATHAM", "LEE", "RANDOLPH", "DAVIDSON", "DAVIE", "ROWAN")

multiple <- c("RUTHERFORD", "FORSYTH", "MECKLENBURG", "MOORE", "CHATHAM", "LEE", "WAKE", "HARNETT", "PITT")

grouped_voter_data <- grouped_voter_data %>% mutate(cong_dist_abbrv = case_when(
    !(county_desc %in% multiple) & county_desc %in% district1 ~ as.integer(1),
    !(county_desc %in% multiple) & county_desc %in% district2 ~ as.integer(2),
    !(county_desc %in% multiple) & county_desc %in% district3 ~ as.integer(3),
    !(county_desc %in% multiple) & county_desc %in% district4 ~ as.integer(4),
    !(county_desc %in% multiple) & county_desc %in% district5 ~ as.integer(5),
    !(county_desc %in% multiple) & county_desc %in% district6 ~ as.integer(6),
    !(county_desc %in% multiple) & county_desc %in% district7 ~ as.integer(7),
    !(county_desc %in% multiple) & county_desc %in% district8 ~ as.integer(8),
    !(county_desc %in% multiple) & county_desc %in% district9 ~ as.integer(9),
    !(county_desc %in% multiple) & county_desc %in% district10 ~ as.integer(10),
    !(county_desc %in% multiple) & county_desc %in% district11 ~ as.integer(11),
    !(county_desc %in% multiple) & county_desc %in% district12 ~ as.integer(12),
    !(county_desc %in% multiple) & county_desc %in% district13 ~ as.integer(13),
    TRUE ~ cong_dist_abbrv
  ))

t <- grouped_voter_data
grouped_voter_data <- t
for (m in multiple){
  for (a in unique(grouped_voter_data$age_bin)){
    for (r in unique(grouped_voter_data$race_ethnicity)){
      for (p in unique(grouped_voter_data$party_cd)){
        for (g in unique(grouped_voter_data$gender))
          {
            curr = grouped_voter_data %>% filter(county_desc==m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & is.na(cong_dist_abbrv))
            if (nrow(curr) == 0){
              next
            }
            curr.dist = grouped_voter_data %>% filter(county_desc==m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & !is.na(cong_dist_abbrv))
            if (nrow(curr.dist) == 0){
              next
            }
            number.dem.from.na <- curr[,7]
            number.rep.from.na <-curr[,8]
            
            all.dem <- number.dem.from.na$Democrat
            add.to.first.dem <- as.integer(all.dem/2)
            
            all.rep <- number.rep.from.na$Republican
            add.to.first.rep <- as.integer(all.rep/2)
            
            first.county <- min(unique(curr.dist$cong_dist_abbrv))
            print(first.county)
            second.county <- max(unique(curr.dist$cong_dist_abbrv))
            
            grouped_voter_data <- grouped_voter_data  %>% 
              mutate(Democrat= case_when(
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == first.county ~ Democrat + add.to.first.dem,
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == second.county ~ Democrat + all.dem - add.to.first.dem,
                TRUE ~ Democrat
              ),
                    Republican=case_when(
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == first.county ~ Republican + add.to.first.rep,
                county_desc == m & age_bin == a & race_ethnicity == r & party_cd == p & gender == g & cong_dist_abbrv == second.county ~ Republican + all.rep - add.to.first.rep,
                TRUE ~ Republican
              ))
            
            
        }

    
      }

    }

  }
  print(m)
  print(nrow(grouped_voter_data))

}
```


```{r setup, include=FALSE}
grouped_voter_only_data <- grouped_voter_data %>% filter(!is.na(cong_dist_abbrv)) 

grouped_voter_only_data %>% write_csv("grouped_voter_only_data_2016.csv")
voter_data %>% filter(is.na(cong_dist_abbrv))
```

