---
title: "Case Study 3 Interim Report: Who Votes in North Carolina?"
author: "Ethan Shen, Malavi Ravindran, Steven Herrera Tenorio, Anna Darwish"
date: "10/13/2020"
output: pdf_document
---

Potential Changes:
- add in h( ) vector for vote share by each state
- focus on only swing states?
- Arizona, Colorado, Florida, Georgia, Iowa, Maine, Michigan, North Carolina, Ohio, Pennsylvania, Texas, and Wisconsin

```{r, function checking for installed packages, include=FALSE}
# Validate that all necessary packaged have been downloaded, install otherwise or throw err package DNE
pkgTest <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,repos = "http://cran.r-project.org", dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}
```

```{r package test, include=FALSE}
# Installing packages 
# Additionally, if you are struggling to download RJags, please visit the following link for help. It can also help to try to download the package locally or in RStudio Cloud: https://sites.google.com/a/utexas.edu/edm-principalstratification/downloading-installing-r-jags-rstudio
pkgTest("ggplot2")
pkgTest("lubridate")
pkgTest("R2jags")
pkgTest("tidyverse")
```

```{r load packages, include=FALSE, results="hide"}
library(ggplot2)
library(lubridate)
library(R2jags)
library(tidyverse)
```


```{r Read in Data}
president_polls <- read_csv("2020 US presidential election polls - all_polls.csv") %>% 
  filter(population %in% c("lv","rv")) %>% 
  mutate(state = ifelse(state == "--","US",state)) %>%
  mutate(pct = biden / (biden + trump) *100) 

#colnames(president_polls)

president_polls <- president_polls %>% 
  mutate(start.date = mdy(start.date),
         end.date = mdy(end.date),
         election_date = "2020-11-03" %>% as.Date(),
         days_to_election = election_date - end.date)

president_polls <- president_polls[president_polls$start.date >= "2020-08-01",]

president_polls <- president_polls %>%
  filter(state %in% c("AZ", "CO", "FL", "GA", "IA", "ME", "MI", "NC", "OH", "PA", "TX", "WI", "MN", "NV", "NH"))

#got rid of US: why? covariance matrix will be hard to estimate
#swing states are: Arizona, Colorado, Florida, Georgia, Iowa, Maine, Michigan, North Carolina, Ohio, Pennsylvania, Texas, Wisconsin, Minnesota, Nevada, New Hampshire
#these were determined from the following map and external sources: https://www.270towin.com/. 
#should we get rid of "US"? The popular vote doesn't really matter anyways. 
```


```{r}
swing <- c("AZ", "CO", "FL", "GA", "IA", "ME", "MI", "NC", "OH", "PA", "TX", "WI", "MN", "NV", "NH")
State_Abbrev[!(State_Abbrev %in% swing)]
```

```{r}
#going to biden:
biden <- c(55, 7, 3, 3, 4, 20, 10, 11, 14, 5, 29, 7, 4, 3, 13, 12)
dem_states <- c("CA", "CT", "DC", "DE", "HI", "IL", "MD", "MA", "NJ", "NM", "NY", "OR", "RI", "VT", "VA", "WA")
votes_going_to_biden <- sum(biden)
votes_going_to_biden
```



```{r}
#which states are not represented at all in polling data? none are swing, so we're good
state_abbreviations <- c("AL", "AK","AZ","AR","CA","CO","CT","DC",
                         "DE","FL","GA","HI","ID","IL","IN","IA","KS",
                         "KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
                         "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK",
                         "OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY")

```



```{r data_list,eval=TRUE}
states <- president_polls$state %>% unique
y <- president_polls$pct
r <- match(president_polls$state,states)
t <- president_polls$days_to_election + 1 
N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max
I_states <- diag(N_states)
```


```{r}
vote_share_2016 <- data.frame(president_polls$state, number = r)
vote_share_2016 <- unique(vote_share_2016) %>%
  mutate(clinton_percent = case_when(
    president_polls.state == "NC" ~ 47/(47 + 51),
    president_polls.state == "MI" ~ 47/(47 + 48),
    president_polls.state == "NH" ~ 48/(48 + 47),
    president_polls.state == "NV" ~ 48/(48 + 46),
    president_polls.state == "PA" ~ 48/(48 + 49),
    president_polls.state == "WI" ~ 47/(47 + 48),
    president_polls.state == "TX" ~ 43/(43 + 53),
    president_polls.state == "OH" ~ 44/(44 + 52),
    president_polls.state == "MN" ~ 47/(47 + 45),
    president_polls.state == "GA" ~ 46/(46 + 51),
    president_polls.state == "FL" ~ 48/(48 + 49),
    president_polls.state == "CO" ~ 47/(47 + 44),
    president_polls.state == "IA" ~ 42/(42 + 52),
    president_polls.state == "ME" ~ 48/(48 + 45),
    president_polls.state == "AZ" ~ 45/(48 + 45)
    
  )) %>%
  mutate(clinton_percent = 100*clinton_percent)
h <- vote_share_2016$clinton_percent

```




```{r Stored and Out Variables in Models}
## The following code stores the list of variables we wish to store in the model Rdata files from the RJAGS code
jags_data <- list("y","t", "r", "N_polls", "N_states", "N_days", "h")
out_parameters = c("beta","sigma2_beta","p","sigma2_y")
```

```{r model,eval = TRUE}
model <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }
  
  
  for(j in 1:N_states){
    sigma2_y[j] = 1/sigma2_y_inv[j]
    sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
    
    sigma2_beta[j] = 1/sigma2_beta_inv[j]
    sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
    beta[j,1] ~ dnorm(h[j],pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
}
```

```{r}
jags_sims <- jags(data = jags_data,model.file = model,parameters.to.save = c("beta","sigma2_beta",
                                                                             "p","sigma2_y"),
                  n.iter = 100)
#jags_sims %>% saveRDS("jags_sims.Rds")
```

Now with estimating correlation structure.

```{r}
jags_data2 <- list("y","t", "r", "N_polls", "N_states", "N_days", "h", "I_states")
#jags_data2 <- list("y","t", "r", "N_polls", "N_states", "N_days", "I_states")
```


```{r model,eval = TRUE}
model2 <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = theta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    theta[1:N_states,j] ~ dmnorm(theta[1:N_states,j-1],Phi)
  }
  
  Phi ~ dwish(I_states,N_states+1) 
  Sigma = inverse(Phi)
  
  #hierarchical component
  
  for(j in 1:N_states){
    sigma2_y[j] = 1/sigma2_y_inv[j]
    sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
    
    theta[j,1] ~ dnorm(h[j], pow(sigma2_0,-1))
    #theta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  #mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(0.5, 0.5)
}
```




```{r}
#jags_data$I_states <- diag(N_states)
jags_sims_mv <- jags(data = jags_data2,model.file = model2,parameters.to.save = c("theta","Sigma",
                                                                                  "p","sigma2_y"),
                     n.iter = 10000)
```


```{r}
n_iter <- dim(jags_sims_mv$BUGSoutput$sims.list$theta[,,1])
```

```{r}
electoral_data <- read.csv("Electoral_College.csv") %>%
  filter(Year == 2020)

electoral_data$states <- c("AL", "AK","AZ","AR","CA","CO","CT","DC",
                           "DE","FL","GA","HI","ID","IL","IN","IA","KS",
                           "KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
                           "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK",
                           "OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY")

#returns number of electoral votes biden wins for each iteration of the sampler
#we need to add to this the votes that he is guaranteed from other states
```


```{r}
prediction_per_simulation <- function(i){
  elec_sims <- jags_sims_mv$BUGSoutput$sims.list$theta[i,,1]
  vote_share_by_state <- data.frame(states, elec_sims)
  
  
  results <- merge(vote_share_by_state, electoral_data, by = "states") %>%
    dplyr::select(-c(Year)) 
  biden_wins <- results %>%
    filter(elec_sims > 50) 
  biden_electoral_votes <- sum(biden_wins$Votes)
  
  #add in the number of guaranteed votes from other states!
  biden_votes = votes_going_to_biden + biden_electoral_votes
  return(biden_votes)
  
}

final_results <- c()

for (i in 1:n_iter){
  final_results[i] = prediction_per_simulation(i)
}

hist(final_results)
mean(final_results >= 270)

```



---------------------OLD-----------------------------

```{r Generate Model Text}
#RJAGs allows users to input either the text of the model they hope to create (where information such as likelihood, priors, and predictive information instructions are necessary) or input an R function. To minimize code duplication, the following method concatenates the likelihood information, prior specification, and predictive information. Anyone who wishes to build off of these results can input the priors (see sections Model 1a - Model 6b for various examples).

generate_model_text = function(hierarchical_priors){
  model_file <- tempfile()
  likelihood_base_priors = "for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }
  
  #EXERCISE: add hierarhciacl prior for sigma2_beta and sigma2_y, i.e. sigma2_beta[j] all come from a common distribution 
  for(j in 1:N_states){
    sigma2_y[j] = 1/sigma2_y_inv[j]
    sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
    
    sigma2_beta[j] = 1/sigma2_beta_inv[j]
    sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
    beta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  "
  
  model_text <- paste("model{ ",likelihood_base_priors, hierarchical_priors,"}")
  writeLines(model_text,con=model_file)
  return(model_file)
}
```

```{r Generate or Load Model}
#The following utility function takes in the priors and name of the model file the user intends to create before running RJAGS. In the case the model_name exists in the current working directory, this function will instead load in that model and return it for further exploration.
generate_model = function(priors,model_name,num_iter = 250000){
  model_file <- generate_model_text(priors)
  if (file.exists(model_name)) {
    load(file = model_name)
  } 
  else {
    rjags_model <-  jags.parallel(data = jags_data,  
                                  parameters.to.save = out_parameters, 
                                  n.iter = num_iter, #increase for better model output - 250K
                                  n.chains = 3,
                                  model.file = model_file)
    save(rjags_model, file = model_name)
  }
  return(rjags_model)
}
```

```{r Original Prior from Lab}
cl <- parallel::makeCluster(3, setup_timeout = 0.5)
priors <- "
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
  "
generate_model(priors,"original_model.Rdata",100)
```



```{r}
poll_plot_data <- tibble(y=jags_data$y,t=jags_data$t %>% as.integer(),state = states[jags_data$r])
beta_plot_data <- lapply(1:N_states,function(st){
  sims <- jags_sims$BUGSoutput$sims.list$beta[,st,]
  data.frame(state = states[st],t=1:N_days,mean=colMeans(sims),lb=apply(sims,2,quantile,probs=.025),ub=apply(sims,2,quantile,probs=.975))
}) %>% 
  bind_rows()
left_join(beta_plot_data,poll_plot_data) %>% 
  ggplot(aes(x=t)) + 
  geom_line(aes(y=mean)) + 
  geom_ribbon(aes(ymin = lb,ymax = ub),alpha = .2) + 
  geom_point(aes(y=y)) + 
  scale_x_reverse() + 
  facet_wrap(~ state)



`%notin%` <- Negate(`%in%`)
elec_sims <- jags_sims$BUGSoutput$sims.list$beta[,,1]
colnames(elec_sims) <- states
(elec_sims) %>% colMeans() #P(Biden Win) each state

elec_sims <- as.data.frame(elec_sims)
elec_sims <- elec_sims[,order(colnames(elec_sims))]

for (s in colnames(elec_sims)) {
  colName <- paste0(s,"_Winner")
  elec_sims[,colName] <- elec_sims[,s] > 50
  elec_sims[,colName] <- as.numeric(elec_sims[,colName])
}

elec_sims <- elec_sims %>% select(-c("US","US_Winner")) 
electoral_data <- read.csv("Electoral_College.csv")
electoral_data <- electoral_data %>% filter(Year == 2020)
electoral_data$State_Abbrev <- c("AL", "AK","AZ","AR","CA","CO","CT","DC",
                                 "DE","FL","GA","HI","ID","IL","IN","IA","KS",
                                 "KY","LA","ME","MD","MA","MI","MN","MS","MO","MT",
                                 "NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK",
                                 "OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY")

predicted_states_winner_colnames <- colnames(elec_sims)[str_detect(colnames(elec_sims), "_Winner")]
predicted_states_abbrev_colnames <- colnames(elec_sims)[!str_detect(colnames(elec_sims), "_Winner")]

predicted_states <- electoral_data %>% filter(State_Abbrev %in% predicted_states_abbrev_colnames)
electoral_votes <- as.matrix(predicted_states$Votes)

elec_sims_winners <- elec_sims %>% select(colnames(elec_sims)[str_detect(colnames(elec_sims), "_Winner")])

elec_sims_matrix <- as.matrix(elec_sims_winners)

remaining_states <- setdiff(electoral_data$State_Abbrev,colnames(elec_sims))
electoral_data %>% filter(State_Abbrev %in% remaining_states)
definitely_democratic <- c(3,20,4)

final_results <- (elec_sims_matrix %*% electoral_votes + sum(definitely_democratic))
```


```{r}
summary(final_results)
hist(final_results)
mean(final_results >= 270)
sd(final_results)
dim(elec_sims_matrix)
dim(electoral_votes)
```



```{r}
for(i in 1:10) {
  print("I want to cry or drink")
}
```

```{r}
nc_voter <- read_rds("ncvoter_Statewide_small.rds")  # all districts, Graham doesnt think it's  all voters, one row for each voter 
head(nc_voter)
nc_voter <- nc_voter %>% 
  filter(voter_status_reason_desc != "DECEASED") %>% 
  mutate(voter_reg_num = as.integer(substr(voter_reg_num,6,12)))
#nc_voter$voter_reg_num <- substr(nc_voter$voter_reg_num,6,12)

nc_reg_data <- read_rds("ncvhis_Statewide_small.rds") # history of every voter in NC

merged_df <- merge(nc_voter,nc_reg_data,by="voter_reg_num")

merged_df %>% filter(voted_party_cd %in% c("REP", "DEM")) %>% group_by(cong_dist_abbrv) %>% count(cong_dist_abbrv, voted_party_cd) %>% summarise(prop=n/sum(n))

district_est <- c(0.59, 0.397, .44, .426, 0.574, 0.379, 0.561, 0.510, 0.576, 0.611, 0.628, 0.377, 0.510)
length(district_est)
sd(district_est)
set.seed(1)

sds_district <- runif(13,1.5,4.2)
district_est*100 - 1.96 * sds_district
district_est*100 + 1.96 * sds_district
```

```{r}
voter_data <- left_join(nc_voter,nc_reg_data %>% filter(voted_party_desc != ""),by=c("voter_reg_num", "county_id", "county_desc"))
#left_voter_reg <- right_join(nc_voter,nc_reg_data,by="voter_reg_num")

voter_data <- voter_data %>% 
  mutate(likely_voter = ifelse(is.na(election_lbl), 0, 1),
         age_bin = case_when(
           birth_age <= 29 ~ "18-29",
           birth_age >= 30 & birth_age <= 39 ~ "30-39",
           birth_age >= 40 & birth_age <= 49 ~ "40-49",
           birth_age >= 50 & birth_age <= 64 ~ "50-64",
           birth_age >= 65 ~ "65+"
         ),
         race_ethnicity = case_when(
           ethnic_code == "HL" ~ "Hispanic Any Race",
           ethnic_code == "NL" & race_code == "W" ~ "Non-Hispanic White",
           ethnic_code == "NL" & race_code == "B" ~ "Non-Hispanic Black",
           ethnic_code == "NL" & race_code == "O" ~ "Non-Hispanic Other",
           ethnic_code == "NL" & race_code == "A" ~ "Non-Hispanic Asian",
           ethnic_code == "NL" & race_code == "M" ~ "Non-Hispanic Mixed",
           ethnic_code == "NL" & race_code == "I" ~ "Non-Hispanic American Indian",
           ethnic_code == "NL" & race_code == "P" ~ "Non-Hispanic Pacific Islander",
           ethnic_code == "NL" & race_code == "U" ~ "Undetermined",
           TRUE ~ "Undetermined"
         ),
         voted_party_desc = case_when(
           voted_party_desc == "DEMOCRATIC" ~ "DEMOCRATIC",
           voted_party_desc == "REPUBLICAN" ~ "REPUBLICAN",
           voted_party_desc== "UNAFFILIATED" ~ "UNAFFILIATED",
           voted_party_desc %in% c("LIBERTARIAN", "GREEN", "CONSTITUTION") ~ "THIRD PARTY",
           TRUE ~ as.character(voted_party_desc)
         )
         
  )

voter_data <- voter_data %>% 
  filter(voted_party_desc != "")

voter_data %>% head()
voter_data$race_code %>% unique()
#left_voter$ethnic_code %>% unique()
# join by 
#1. county_id, 2. age bins, 3. race_code, 4. ethnic_code 5. combining race and ethnic code, 5. voted_party_cd, 6. gender if possible 

#18-29 
#29-39
#39-49
#49-65
```


```{r}
#65+
#voting method for sensitivity
```
```{r}
voter_data %>%
  count(voted_party_desc)
```

```{r}
grouped_voter_data <- voter_data %>%
  group_by(county_desc, race_ethnicity, #voted_party_desc, 
           age_bin, gender_code) %>%
  summarize(Likely = sum(likely_voter==1), 
            unlikely = sum(likely_voter == 0),
            total = n())
```

```{r}
grouped_voter_data %>% write_csv("grouped_voter_data.csv")
```

```{r}
voter_data %>% filter(county_desc == "ALAMANCE",
                      race_code = "A",
                      ethnic_code)
```



```{r}
library(brms)
library(optimx)
who_votes_data <- readRDS("who_votes_data.Rds")
# adm3 <- brm(data = who_votes_data, family = binomial,
#             Likely | trials(Likely + Unlikely) ~ 1 + age_bin + (1 | gender),
#             iter = 500, chains = 1, cores = 4,
#             seed = 13,
#             control = list(adapt_delta = .99,
#                            max_treedepth = 12))



library(lme4)
library(plyr)
library(lmerTest)
library(glmnet)
m1 <- lmer(prop ~ age_bin + race_ethnicity + gender + (1  | county_desc), 
           data = who_votes_data %>% mutate(prop = Likely / (Likely + Unlikely)), 
           control = lmerControl(optimizer = "optimx", calc.derivs = FALSE, optCtrl = list(method = "nlminb", starttests=FALSE, kkt=FALSE)))
m1 %>% summary()

who_votes_data$age_bin <- relevel(who_votes_data$age_bin %>% as.factor(), ref = "40-49")
m2 <- glmer(prop ~ age_bin + race_ethnicity + gender * race_ethnicity + gender + (1 | county_desc), 
            data = who_votes_data %>% mutate(prop = Likely / (Likely + Unlikely)), 
            family = binomial, weights = Likely + Unlikely, 
            control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)))
m2 %>% summary() # get to the fucking point
```

```{r}
library(groupdata2)

accuracy_list <- c()
fold_df <- groupdata2::fold(who_votes_data, k = 5, cat_col = c("age_bin", "race_ethnicity", "gender","county_desc"))

for (i in 1:5) {
  train <- fold_df %>% filter(.folds != i)
  test <- fold_df %>% filter(.folds == i)
  
  m.fit <- glmer(prop ~ age_bin + race_ethnicity + #gender * race_ethnicity + 
                   gender + (1 | gender), 
                 data = train, 
                 family = binomial, weights = Likely + Unlikely, 
                 control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)))
  
  m.probs <- predict(m.fit,  test,  type = "response")
  m.pred <- rep(0,  nrow(test))
  m.pred[m.probs > 0.5] <- 1
}

```



```{r out.width="75%",out.height="75%",fig.show='hold',fig.align='center',fig.cap="Representation of the interval estimates of the random effects"}
merTools::plotREsim(merTools::REsim(m2)) %>% +
  labs(x='Student', y='Value', title='Interval Estimates of Random Effects by Student') +
  geom_hline(aes(yintercept=0), color='orange', alpha=.5) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.x = element_blank(),
        strip.text.y = element_blank(),
        panel.background = element_rect(fill='transparent', color=NA),   # apparently all ignored for reasons unknown
        plot.background = element_rect(fill='transparent', color=NA),
        strip.background =  element_rect(fill='transparent', color=NA))
```



```{r}

sjPlot::plot_model(m2,
                   show.values=TRUE, show.p=TRUE, jitter = TRUE, 
                   dot.size = 1, value.offset = 0.35,value.size = 3, wrap.title = 100,
                   title="can i get a waffle")
```

```{r}
#covid.df.county <- covid.df[!is.na(covid.df$county_name), ]
results <- data.frame(VarCorr(m1))
random.effects.results <- data.frame("Intercept"=c(round(results[1,4],3)),"Std.Dev"=c(round(results[1,5],3)))

rand.county.mod.results = data.frame(Estimates=summary(m1)$coefficients[, 1], 
                                     Std.Err=summary(m1)$coefficients[, 2], 
                                     P.Value=summary(m1)$coefficients[, 3])
pander(m1, caption = "Random County Effects Model")
```

```{r}
sjPlot::tab_model(m2, 
                  show.re.var= TRUE,
                  dv.labels= "plz can i get a waffle", p.style = "numeric_stars")
```
